# This project uses _clippy_ to lint its code.
#
# You can install it with the following command:
# ```
# rustup component add clippy
# ```
#
# You can run it with the following command:
# ```
# cargo clippy --all-targets --all-features -- -D warnings
# ```
