[package]
name = "txgenerator"
version = "0.1.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
license = "AGPL-3.0-or-later"
edition = "2018"

[dependencies]
txdemo = { path = "../" }
rand = "0.8.4"
rand_distr = "0.4.2"
rand_pcg = "0.3.1"
rayon = "1.5.1"
sha2 = "0.9.8"
