name: Check the Rust code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust-version: ["1.55.0"]

    steps:
      - uses: actions/checkout@v2

      - name: Use Rust ${{ matrix.rust-version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          components: rustfmt, clippy

      - name: Build and test
        uses: actions-rs/tarpaulin@v0.1
        with:
          out-type: "lcov"
          args: "--count"

      - name: Upload coverage report to codecov.io
        uses: codecov/codecov-action@v2
        with:
          # It's important to set this field otherwiser it will try to upload
          # our test resources.
          files: "./lcov.info"

      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Lint the project
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings

      - name: Run a security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
